/**
 * @file task.h
 * @brief Task schema for multi-agent orchestration (ADR-096).
 *
 * Defines the structured task plan that flows between Planner, Executor, and
 * Reviewer agents.
 */

#ifndef ORCHESTRATOR_TASK_H
#define ORCHESTRATOR_TASK_H

#include <string>
#include <vector>

/// Tool type for a task step.
enum class Tool { Read, Write, StrReplace, Exec, Git };

/// Status of a task step or plan.
enum class Status { Pending, Running, Completed, Failed, Skipped };

/// A single step in a task plan.
struct TaskStep {
  int id = 0;                                              ///< Step sequence number
  Tool tool = Tool::Read;                                  ///< Tool to use for this step
  std::string action;                                      ///< Human-readable description
  std::vector<std::pair<std::string, std::string>> input;  ///< Key-value params (path, cmd, old, new, etc.)
  Status status = Status::Pending;                         ///< Current execution status
  std::string result;                                      ///< Output after execution
  int retries = 0;                                         ///< Number of retry attempts
};

/// A complete task plan generated by the Planner agent.
struct TaskPlan {
  std::string goal;                 ///< Original user request
  std::vector<TaskStep> steps;      ///< Ordered list of steps
  Status status = Status::Pending;  ///< Overall plan status
};

/// Parse a JSON task plan string into a TaskPlan struct.
/// Returns empty plan (no steps) on parse failure.
TaskPlan parse_task_plan(const std::string& json);

/// Serialize a TaskPlan to JSON string (for logging/debugging).
std::string serialize_task_plan(const TaskPlan& plan);

/// Convert Tool enum to string.
std::string tool_to_string(Tool t);

/// Parse string to Tool enum. Returns Tool::Read on unknown.
Tool string_to_tool(const std::string& s);

/// Convert Status enum to string.
std::string status_to_string(Status s);

#endif  // ORCHESTRATOR_TASK_H
