# git-cliff configuration
[changelog]
# Header format
header = """
# Changelog\n
"""
# Footer format
footer = ""
# Sort commits
sort = "newest"

# Changelog sections
[[changelog.sections]]
group = "💥 Breaking Changes"
filter = "^.*!:.*"

[[changelog.sections]]
group = "🚀 Features"
filter = "^feat"

[[changelog.sections]]
group = "🐛 Bug Fixes"
filter = "^fix"

[[changelog.sections]]
group = "📚 Documentation"
filter = "^doc"

[[changelog.sections]]
group = "⚡ Performance"
filter = "^perf"

[[changelog.sections]]
group = "♻️ Refactoring"
filter = "^refactor"

[[changelog.sections]]
group = "✅ Testing"
filter = "^test"

[[changelog.sections]]
group = "🔧 Build"
filter = "^build|^ci"

[[changelog.sections]]
group = "🔨 Other"
filter = "^chore|^style"

[git]
# Parse commits
conventional_commits = true
# Filter out commits
filter_unconventional = true
# Tag prefix
tag_prefix = "v"
# Regex to ignore tags
ignore_tags = ""