#!/usr/bin/env bash
#
# scrape-todo.sh — Scrapes TODO and FIXME comments to track technical debt.
#
# Part of CMMI 1 implementation (Check 1.3)
#

set -o errexit
set -o nounset
set -o pipefail

source lib/cpm/shell/init.sh 2>/dev/null || true

TECHDEBT_FILE="TECHDEBT.md"
SRC_DIR="src"

echo "# Technical Debt Report - $(date +%Y-%m-%d)" >"$TECHDEBT_FILE"
echo "" >>"$TECHDEBT_FILE"
echo "| Type | File | Line | Content |" >>"$TECHDEBT_FILE"
echo "|------|------|------|---------|" >>"$TECHDEBT_FILE"

# Search for TODO and FIXME in C++ files
# Format: | TODO | src/file.cpp | 42 | description |
grep -rE "TODO|FIXME" "$SRC_DIR" --include="*.cpp" --include="*.h" | while read -r line; do
  file=$(echo "$line" | cut -d: -f1)
  content=$(echo "$line" | cut -d: -f2-)
  line_num=$(echo "$line" | cut -d: -f1) # This is tricky with grep -r output

  # Re-parsing for cleaner output
  actual_line_num=$(grep -nF "$content" "$file" | cut -d: -f1 | head -n1)

  type=$(echo "$content" | grep -oE "TODO|FIXME")
  clean_content=$(echo "$content" | sed 's/^[[:space:]]*//')

  echo "| $type | $file | $actual_line_num | $clean_content |" >>"$TECHDEBT_FILE"
done

echo "" >>"$TECHDEBT_FILE"
echo "Generated by: $(basename "$0")" >>"$TECHDEBT_FILE"
