#!/usr/bin/env bash
#
# todo.sh — Show TODO items from markdown files and source code.
#
# Usage:
#   bash scripts/dev/todo.sh
#
# @see docs/adr/adr-44-tidy-boilerplate.md

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

main() {
  echo "==> Markdown TODOs"
  find . -name "*.md" -not -path "./build/*" -not -path "./.git/*" -exec awk '
    FNR == 1 {
      if (prev_line != "") printf "%s:%d:%s\n", prev_file, prev_lnum, prev_line;
      prev_line = "";
    }
    /- \[ \]/ {
      match($0, /[^ ]/);
      curr_indent = RSTART;
      if (prev_line != "") {
        if (curr_indent > prev_indent) {
          printf "%s:%d:\033[1m%s\033[0m\n", FILENAME, prev_lnum, prev_line;
        } else {
          printf "%s:%d:%s\n", FILENAME, prev_lnum, prev_line;
        }
      }
      prev_line = $0;
      prev_indent = curr_indent;
      prev_lnum = FNR;
      prev_file = FILENAME;
    }
    END {
      if (prev_line != "") printf "%s:%d:%s\n", FILENAME, prev_lnum, prev_line;
    }' {} +

  echo ""
  echo "==> Code TODOs"
  local code_todos
  code_todos=$(grep -rn -E '\b(TODO|FIXME|HACK|XXX)\b' src/ include/ --include="*.cpp" --include="*.h" 2>/dev/null || true)
  echo "${code_todos}"

  # Generate TECHDEBT.md
  # @see docs/adr/adr-048-quality-framework.md §3.3 check 1.3
  {
    echo "# Technical Debt Log"
    echo ""
    echo "Auto-generated by \`make todo\` on $(date -u +%Y-%m-%d)."
    echo ""
    echo "## Code TODOs"
    echo ""
    local code_count=0
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      echo "- \`${line//\`/\\\`}\`"
      (( code_count++ )) || true
    done <<< "${code_todos}"
    echo ""
    echo "**Total code TODOs: ${code_count}**"
    echo ""
    echo "## Markdown TODOs (unchecked items)"
    echo ""
    local md_count=0
    while IFS= read -r line; do
      echo "- \`${line//\`/\\\`}\`"
      (( md_count++ )) || true
    done < <(grep -rn "\- \[ \]" . --include="*.md" --exclude-dir=build --exclude-dir=.git --exclude-dir=.cache --exclude-dir=.tmp --exclude-dir=.github --exclude="TECHDEBT.md" 2>/dev/null || true)
    echo ""
    echo "**Total markdown TODOs: ${md_count}**"
  } > TECHDEBT.md

  echo ""
  echo "==> TECHDEBT.md updated"
  git add ./TECHDEBT.md
}

main "$@"
